#!/usr/bin/env python3
def make_maze(length, height):
    positions = [[1] + [0] * (length - 2) + [1] for count in range(height-1)] + [[1] * length]
    print(positions)
    startpos = (0,0)


make_maze(5,5)
