#!/usr/bin/env python3
import random
def make_maze(length, height):
    positions = [[0] * length for count in range(height)]

    horizontal = [['###'] * length for count in range(height)]
    vertical = [['#  '] * length for count in range(height)]
    print(positions)
    walk(0,0)
    def walk(x,y):
        positions[y][x] = 1 #visited
        directions = [(x - 1, y), (x, y + 1), (x + 1, y), (x, y - 1)]
        random.shuffle(directions)
        for (newx,newy) in directions:
            if positions[newy][newx]: #1 == true, so if visited
                continue
            elif y != newy:
                horizontal[newy][newx] = '# #'
            else:
                vertical[newy][newx] = '  ' 
            walk(newx,newy,hor,positions) 
    for (a,b) in zip(horizontal,vertical):
        print(a + '\n' + b + '\n')
make_maze(5,5)
