#!/usr/bin/env python3

import sys, tty, termios
#http://stackoverflow.com/questions/510357/python-read-a-single-character-from-the-user
def get_char():
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    return ch
 
char = ord(get_char())

